namespace GameStore.DataAccess.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class Adding_New_Field_To_BaseEntity_All_Id_Is_Guid : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.CommentEntities", "GameId", "dbo.GameEntities");
            DropForeignKey("dbo.OrderDetailsEntities", "GameId", "dbo.GameEntities");
            DropForeignKey("dbo.OrderDetailsEntities", "OrderId", "dbo.OrderEntities");
            DropForeignKey("dbo.GameInfoEntities", "Id", "dbo.GameEntities");
            DropForeignKey("dbo.GenreEntityGameEntities", "GameEntity_Id", "dbo.GameEntities");
            DropForeignKey("dbo.PlatformTypeEntityGameEntities", "GameEntity_Id", "dbo.GameEntities");
            DropForeignKey("dbo.GenreEntityGameEntities", "GenreEntity_Id", "dbo.GenreEntities");
            DropForeignKey("dbo.GenreEntities", "GenreEntity_Id", "dbo.GenreEntities");
            DropForeignKey("dbo.PlatformTypeEntityGameEntities", "PlatformTypeEntity_Id", "dbo.PlatformTypeEntities");
            DropForeignKey("dbo.GameEntities", "Publisher_Id", "dbo.PublisherEntities");
            DropIndex("dbo.CommentEntities", new[] { "GameId" });
            DropIndex("dbo.GameEntities", new[] { "Publisher_Id" });
            DropIndex("dbo.GameInfoEntities", new[] { "Id" });
            DropIndex("dbo.GenreEntities", new[] { "GenreEntity_Id" });
            DropIndex("dbo.OrderDetailsEntities", new[] { "GameId" });
            DropIndex("dbo.OrderDetailsEntities", new[] { "OrderId" });
            DropIndex("dbo.GenreEntityGameEntities", new[] { "GenreEntity_Id" });
            DropIndex("dbo.GenreEntityGameEntities", new[] { "GameEntity_Id" });
            DropIndex("dbo.PlatformTypeEntityGameEntities", new[] { "PlatformTypeEntity_Id" });
            DropIndex("dbo.PlatformTypeEntityGameEntities", new[] { "GameEntity_Id" });
            RenameColumn(table: "dbo.GameInfoEntities", name: "Id", newName: "EntityId");
            RenameColumn(table: "dbo.GenreEntityGameEntities", name: "GenreEntity_Id", newName: "GenreEntity_EntityId");
            RenameColumn(table: "dbo.GenreEntityGameEntities", name: "GameEntity_Id", newName: "GameEntity_EntityId");
            RenameColumn(table: "dbo.PlatformTypeEntityGameEntities", name: "PlatformTypeEntity_Id", newName: "PlatformTypeEntity_EntityId");
            RenameColumn(table: "dbo.PlatformTypeEntityGameEntities", name: "GameEntity_Id", newName: "GameEntity_EntityId");
            RenameColumn(table: "dbo.GameEntities", name: "Publisher_Id", newName: "Publisher_EntityId");
            RenameColumn(table: "dbo.GenreEntities", name: "GenreEntity_Id", newName: "GenreEntity_EntityId");
            DropPrimaryKey("dbo.CommentEntities");
            DropPrimaryKey("dbo.GameEntities");
            DropPrimaryKey("dbo.GameInfoEntities");
            DropPrimaryKey("dbo.GenreEntities");
            DropPrimaryKey("dbo.PlatformTypeEntities");
            DropPrimaryKey("dbo.PublisherEntities");
            DropPrimaryKey("dbo.OrderDetailsEntities");
            DropPrimaryKey("dbo.OrderEntities");
            DropPrimaryKey("dbo.GenreEntityGameEntities");
            DropPrimaryKey("dbo.PlatformTypeEntityGameEntities");
            AddColumn("dbo.CommentEntities", "EntityId", c => c.String(nullable: false, maxLength: 128));
            AddColumn("dbo.CommentEntities", "IsSqlEntity", c => c.Boolean(nullable: false));
            AddColumn("dbo.CommentEntities", "Game_EntityId", c => c.String(maxLength: 128));
            AddColumn("dbo.GameEntities", "EntityId", c => c.String(nullable: false, maxLength: 128));
            AddColumn("dbo.GameEntities", "IsSqlEntity", c => c.Boolean(nullable: false));
            AddColumn("dbo.GameInfoEntities", "IsSqlEntity", c => c.Boolean(nullable: false));
            AddColumn("dbo.GenreEntities", "EntityId", c => c.String(nullable: false, maxLength: 128));
            AddColumn("dbo.GenreEntities", "IsSqlEntity", c => c.Boolean(nullable: false));
            AddColumn("dbo.PlatformTypeEntities", "EntityId", c => c.String(nullable: false, maxLength: 128));
            AddColumn("dbo.PlatformTypeEntities", "IsSqlEntity", c => c.Boolean(nullable: false));
            AddColumn("dbo.PublisherEntities", "EntityId", c => c.String(nullable: false, maxLength: 128));
            AddColumn("dbo.PublisherEntities", "IsSqlEntity", c => c.Boolean(nullable: false));
            AddColumn("dbo.OrderDetailsEntities", "EntityId", c => c.String(nullable: false, maxLength: 128));
            AddColumn("dbo.OrderDetailsEntities", "IsSqlEntity", c => c.Boolean(nullable: false));
            AddColumn("dbo.OrderDetailsEntities", "Game_EntityId", c => c.String(maxLength: 128));
            AddColumn("dbo.OrderDetailsEntities", "Order_EntityId", c => c.String(maxLength: 128));
            AddColumn("dbo.OrderEntities", "EntityId", c => c.String(nullable: false, maxLength: 128));
            AddColumn("dbo.OrderEntities", "IsSqlEntity", c => c.Boolean(nullable: false));
            AlterColumn("dbo.CommentEntities", "ParentCommentId", c => c.String());
            AlterColumn("dbo.CommentEntities", "GameId", c => c.String());
            AlterColumn("dbo.GameEntities", "Publisher_EntityId", c => c.String(maxLength: 128));
            AlterColumn("dbo.GameInfoEntities", "EntityId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.GenreEntities", "ParentGenreId", c => c.String());
            AlterColumn("dbo.GenreEntities", "GenreEntity_EntityId", c => c.String(maxLength: 128));
            AlterColumn("dbo.OrderDetailsEntities", "GameId", c => c.String());
            AlterColumn("dbo.OrderDetailsEntities", "OrderId", c => c.String());
            AlterColumn("dbo.OrderEntities", "CustomerId", c => c.String());
            AlterColumn("dbo.GenreEntityGameEntities", "GenreEntity_EntityId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.GenreEntityGameEntities", "GameEntity_EntityId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.PlatformTypeEntityGameEntities", "PlatformTypeEntity_EntityId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.PlatformTypeEntityGameEntities", "GameEntity_EntityId", c => c.String(nullable: false, maxLength: 128));
            AddPrimaryKey("dbo.CommentEntities", "EntityId");
            AddPrimaryKey("dbo.GameEntities", "EntityId");
            AddPrimaryKey("dbo.GameInfoEntities", "EntityId");
            AddPrimaryKey("dbo.GenreEntities", "EntityId");
            AddPrimaryKey("dbo.PlatformTypeEntities", "EntityId");
            AddPrimaryKey("dbo.PublisherEntities", "EntityId");
            AddPrimaryKey("dbo.OrderDetailsEntities", "EntityId");
            AddPrimaryKey("dbo.OrderEntities", "EntityId");
            AddPrimaryKey("dbo.GenreEntityGameEntities", new[] { "GenreEntity_EntityId", "GameEntity_EntityId" });
            AddPrimaryKey("dbo.PlatformTypeEntityGameEntities", new[] { "PlatformTypeEntity_EntityId", "GameEntity_EntityId" });
            CreateIndex("dbo.CommentEntities", "Game_EntityId");
            CreateIndex("dbo.GameEntities", "Publisher_EntityId");
            CreateIndex("dbo.GameInfoEntities", "EntityId");
            CreateIndex("dbo.GenreEntities", "GenreEntity_EntityId");
            CreateIndex("dbo.OrderDetailsEntities", "Game_EntityId");
            CreateIndex("dbo.OrderDetailsEntities", "Order_EntityId");
            CreateIndex("dbo.GenreEntityGameEntities", "GenreEntity_EntityId");
            CreateIndex("dbo.GenreEntityGameEntities", "GameEntity_EntityId");
            CreateIndex("dbo.PlatformTypeEntityGameEntities", "PlatformTypeEntity_EntityId");
            CreateIndex("dbo.PlatformTypeEntityGameEntities", "GameEntity_EntityId");
            AddForeignKey("dbo.CommentEntities", "Game_EntityId", "dbo.GameEntities", "EntityId");
            AddForeignKey("dbo.OrderDetailsEntities", "Game_EntityId", "dbo.GameEntities", "EntityId");
            AddForeignKey("dbo.OrderDetailsEntities", "Order_EntityId", "dbo.OrderEntities", "EntityId");
            AddForeignKey("dbo.GameInfoEntities", "EntityId", "dbo.GameEntities", "EntityId");
            AddForeignKey("dbo.GenreEntityGameEntities", "GameEntity_EntityId", "dbo.GameEntities", "EntityId", cascadeDelete: true);
            AddForeignKey("dbo.PlatformTypeEntityGameEntities", "GameEntity_EntityId", "dbo.GameEntities", "EntityId", cascadeDelete: true);
            AddForeignKey("dbo.GenreEntityGameEntities", "GenreEntity_EntityId", "dbo.GenreEntities", "EntityId", cascadeDelete: true);
            AddForeignKey("dbo.GenreEntities", "GenreEntity_EntityId", "dbo.GenreEntities", "EntityId");
            AddForeignKey("dbo.PlatformTypeEntityGameEntities", "PlatformTypeEntity_EntityId", "dbo.PlatformTypeEntities", "EntityId", cascadeDelete: true);
            AddForeignKey("dbo.GameEntities", "Publisher_EntityId", "dbo.PublisherEntities", "EntityId");
            DropColumn("dbo.CommentEntities", "Id");
            DropColumn("dbo.GameEntities", "Id");
            DropColumn("dbo.GenreEntities", "Id");
            DropColumn("dbo.PlatformTypeEntities", "Id");
            DropColumn("dbo.PublisherEntities", "Id");
            DropColumn("dbo.OrderDetailsEntities", "Id");
            DropColumn("dbo.OrderEntities", "Id");
        }
        
        public override void Down()
        {
            AddColumn("dbo.OrderEntities", "Id", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.OrderDetailsEntities", "Id", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.PublisherEntities", "Id", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.PlatformTypeEntities", "Id", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.GenreEntities", "Id", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.GameEntities", "Id", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.CommentEntities", "Id", c => c.Int(nullable: false, identity: true));
            DropForeignKey("dbo.GameEntities", "Publisher_EntityId", "dbo.PublisherEntities");
            DropForeignKey("dbo.PlatformTypeEntityGameEntities", "PlatformTypeEntity_EntityId", "dbo.PlatformTypeEntities");
            DropForeignKey("dbo.GenreEntities", "GenreEntity_EntityId", "dbo.GenreEntities");
            DropForeignKey("dbo.GenreEntityGameEntities", "GenreEntity_EntityId", "dbo.GenreEntities");
            DropForeignKey("dbo.PlatformTypeEntityGameEntities", "GameEntity_EntityId", "dbo.GameEntities");
            DropForeignKey("dbo.GenreEntityGameEntities", "GameEntity_EntityId", "dbo.GameEntities");
            DropForeignKey("dbo.GameInfoEntities", "EntityId", "dbo.GameEntities");
            DropForeignKey("dbo.OrderDetailsEntities", "Order_EntityId", "dbo.OrderEntities");
            DropForeignKey("dbo.OrderDetailsEntities", "Game_EntityId", "dbo.GameEntities");
            DropForeignKey("dbo.CommentEntities", "Game_EntityId", "dbo.GameEntities");
            DropIndex("dbo.PlatformTypeEntityGameEntities", new[] { "GameEntity_EntityId" });
            DropIndex("dbo.PlatformTypeEntityGameEntities", new[] { "PlatformTypeEntity_EntityId" });
            DropIndex("dbo.GenreEntityGameEntities", new[] { "GameEntity_EntityId" });
            DropIndex("dbo.GenreEntityGameEntities", new[] { "GenreEntity_EntityId" });
            DropIndex("dbo.OrderDetailsEntities", new[] { "Order_EntityId" });
            DropIndex("dbo.OrderDetailsEntities", new[] { "Game_EntityId" });
            DropIndex("dbo.GenreEntities", new[] { "GenreEntity_EntityId" });
            DropIndex("dbo.GameInfoEntities", new[] { "EntityId" });
            DropIndex("dbo.GameEntities", new[] { "Publisher_EntityId" });
            DropIndex("dbo.CommentEntities", new[] { "Game_EntityId" });
            DropPrimaryKey("dbo.PlatformTypeEntityGameEntities");
            DropPrimaryKey("dbo.GenreEntityGameEntities");
            DropPrimaryKey("dbo.OrderEntities");
            DropPrimaryKey("dbo.OrderDetailsEntities");
            DropPrimaryKey("dbo.PublisherEntities");
            DropPrimaryKey("dbo.PlatformTypeEntities");
            DropPrimaryKey("dbo.GenreEntities");
            DropPrimaryKey("dbo.GameInfoEntities");
            DropPrimaryKey("dbo.GameEntities");
            DropPrimaryKey("dbo.CommentEntities");
            AlterColumn("dbo.PlatformTypeEntityGameEntities", "GameEntity_EntityId", c => c.Int(nullable: false));
            AlterColumn("dbo.PlatformTypeEntityGameEntities", "PlatformTypeEntity_EntityId", c => c.Int(nullable: false));
            AlterColumn("dbo.GenreEntityGameEntities", "GameEntity_EntityId", c => c.Int(nullable: false));
            AlterColumn("dbo.GenreEntityGameEntities", "GenreEntity_EntityId", c => c.Int(nullable: false));
            AlterColumn("dbo.OrderEntities", "CustomerId", c => c.Int(nullable: false));
            AlterColumn("dbo.OrderDetailsEntities", "OrderId", c => c.Int(nullable: false));
            AlterColumn("dbo.OrderDetailsEntities", "GameId", c => c.Int(nullable: false));
            AlterColumn("dbo.GenreEntities", "GenreEntity_EntityId", c => c.Int());
            AlterColumn("dbo.GenreEntities", "ParentGenreId", c => c.Int());
            AlterColumn("dbo.GameInfoEntities", "EntityId", c => c.Int(nullable: false));
            AlterColumn("dbo.GameEntities", "Publisher_EntityId", c => c.Int());
            AlterColumn("dbo.CommentEntities", "GameId", c => c.Int(nullable: false));
            AlterColumn("dbo.CommentEntities", "ParentCommentId", c => c.Int());
            DropColumn("dbo.OrderEntities", "IsSqlEntity");
            DropColumn("dbo.OrderEntities", "EntityId");
            DropColumn("dbo.OrderDetailsEntities", "Order_EntityId");
            DropColumn("dbo.OrderDetailsEntities", "Game_EntityId");
            DropColumn("dbo.OrderDetailsEntities", "IsSqlEntity");
            DropColumn("dbo.OrderDetailsEntities", "EntityId");
            DropColumn("dbo.PublisherEntities", "IsSqlEntity");
            DropColumn("dbo.PublisherEntities", "EntityId");
            DropColumn("dbo.PlatformTypeEntities", "IsSqlEntity");
            DropColumn("dbo.PlatformTypeEntities", "EntityId");
            DropColumn("dbo.GenreEntities", "IsSqlEntity");
            DropColumn("dbo.GenreEntities", "EntityId");
            DropColumn("dbo.GameInfoEntities", "IsSqlEntity");
            DropColumn("dbo.GameEntities", "IsSqlEntity");
            DropColumn("dbo.GameEntities", "EntityId");
            DropColumn("dbo.CommentEntities", "Game_EntityId");
            DropColumn("dbo.CommentEntities", "IsSqlEntity");
            DropColumn("dbo.CommentEntities", "EntityId");
            AddPrimaryKey("dbo.PlatformTypeEntityGameEntities", new[] { "PlatformTypeEntity_Id", "GameEntity_Id" });
            AddPrimaryKey("dbo.GenreEntityGameEntities", new[] { "GenreEntity_Id", "GameEntity_Id" });
            AddPrimaryKey("dbo.OrderEntities", "Id");
            AddPrimaryKey("dbo.OrderDetailsEntities", "Id");
            AddPrimaryKey("dbo.PublisherEntities", "Id");
            AddPrimaryKey("dbo.PlatformTypeEntities", "Id");
            AddPrimaryKey("dbo.GenreEntities", "Id");
            AddPrimaryKey("dbo.GameInfoEntities", "Id");
            AddPrimaryKey("dbo.GameEntities", "Id");
            AddPrimaryKey("dbo.CommentEntities", "Id");
            RenameColumn(table: "dbo.GenreEntities", name: "GenreEntity_EntityId", newName: "GenreEntity_Id");
            RenameColumn(table: "dbo.GameEntities", name: "Publisher_EntityId", newName: "Publisher_Id");
            RenameColumn(table: "dbo.PlatformTypeEntityGameEntities", name: "GameEntity_EntityId", newName: "GameEntity_Id");
            RenameColumn(table: "dbo.PlatformTypeEntityGameEntities", name: "PlatformTypeEntity_EntityId", newName: "PlatformTypeEntity_Id");
            RenameColumn(table: "dbo.GenreEntityGameEntities", name: "GameEntity_EntityId", newName: "GameEntity_Id");
            RenameColumn(table: "dbo.GenreEntityGameEntities", name: "GenreEntity_EntityId", newName: "GenreEntity_Id");
            RenameColumn(table: "dbo.GameInfoEntities", name: "EntityId", newName: "Id");
            CreateIndex("dbo.PlatformTypeEntityGameEntities", "GameEntity_Id");
            CreateIndex("dbo.PlatformTypeEntityGameEntities", "PlatformTypeEntity_Id");
            CreateIndex("dbo.GenreEntityGameEntities", "GameEntity_Id");
            CreateIndex("dbo.GenreEntityGameEntities", "GenreEntity_Id");
            CreateIndex("dbo.OrderDetailsEntities", "OrderId");
            CreateIndex("dbo.OrderDetailsEntities", "GameId");
            CreateIndex("dbo.GenreEntities", "GenreEntity_Id");
            CreateIndex("dbo.GameInfoEntities", "Id");
            CreateIndex("dbo.GameEntities", "Publisher_Id");
            CreateIndex("dbo.CommentEntities", "GameId");
            AddForeignKey("dbo.GameEntities", "Publisher_Id", "dbo.PublisherEntities", "Id");
            AddForeignKey("dbo.PlatformTypeEntityGameEntities", "PlatformTypeEntity_Id", "dbo.PlatformTypeEntities", "Id", cascadeDelete: true);
            AddForeignKey("dbo.GenreEntities", "GenreEntity_Id", "dbo.GenreEntities", "Id");
            AddForeignKey("dbo.GenreEntityGameEntities", "GenreEntity_Id", "dbo.GenreEntities", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PlatformTypeEntityGameEntities", "GameEntity_Id", "dbo.GameEntities", "Id", cascadeDelete: true);
            AddForeignKey("dbo.GenreEntityGameEntities", "GameEntity_Id", "dbo.GameEntities", "Id", cascadeDelete: true);
            AddForeignKey("dbo.GameInfoEntities", "Id", "dbo.GameEntities", "Id");
            AddForeignKey("dbo.OrderDetailsEntities", "OrderId", "dbo.OrderEntities", "Id", cascadeDelete: true);
            AddForeignKey("dbo.OrderDetailsEntities", "GameId", "dbo.GameEntities", "Id", cascadeDelete: true);
            AddForeignKey("dbo.CommentEntities", "GameId", "dbo.GameEntities", "Id", cascadeDelete: true);
        }
    }
}
