// <auto-generated />
namespace GameStore.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class new_columns_to_games : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(new_columns_to_games));
        
        string IMigrationMetadata.Id
        {
            get { return "201707181541158_new_columns_to_games"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
