// <auto-generated />
namespace GameStore.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Adding_New_Field_To_BaseEntity_All_Id_Is_Guid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Adding_New_Field_To_BaseEntity_All_Id_Is_Guid));
        
        string IMigrationMetadata.Id
        {
            get { return "201708040844571_Adding_New _Field_To_BaseEntity_All_Id_Is_Guid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
