// <auto-generated />
namespace GameStore.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Key_as_primaryKey_Games : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Key_as_primaryKey_Games));
        
        string IMigrationMetadata.Id
        {
            get { return "201707170814379_Key_as_primaryKey_Games"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
