// <auto-generated />
namespace GameStore.DataAccess.MSSQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_User_Reference_to_OrderEntity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_User_Reference_to_OrderEntity));
        
        string IMigrationMetadata.Id
        {
            get { return "201708141313547_add_User_Reference_to_OrderEntity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
