// <auto-generated />
namespace GameStore.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IENUMARABLE_TO_LIST : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IENUMARABLE_TO_LIST));
        
        string IMigrationMetadata.Id
        {
            get { return "201707121404165_IENUMARABLE_TO_LIST"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
