// <auto-generated />
namespace GameStore.DataAccess.MSSQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IsDisabled_field_to_CommentEntity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IsDisabled_field_to_CommentEntity));
        
        string IMigrationMetadata.Id
        {
            get { return "201708290858518_IsDisabled_field_to_CommentEntity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
