namespace GameStore.DataAccess.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class Rename_Primary_Key : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.CommentEntities", "Game_EntityId", "dbo.GameEntities");
            DropForeignKey("dbo.GameInfoEntities", "EntityId", "dbo.GameEntities");
            DropForeignKey("dbo.GenreEntityGameEntities", "GameEntity_EntityId", "dbo.GameEntities");
            DropForeignKey("dbo.PlatformTypeEntityGameEntities", "GameEntity_EntityId", "dbo.GameEntities");
            DropForeignKey("dbo.OrderDetailsEntities", "Game_EntityId", "dbo.GameEntities");
            DropForeignKey("dbo.GenreEntityGameEntities", "GenreEntity_EntityId", "dbo.GenreEntities");
            DropForeignKey("dbo.GenreEntities", "GenreEntity_EntityId", "dbo.GenreEntities");
            DropForeignKey("dbo.PlatformTypeEntityGameEntities", "PlatformTypeEntity_EntityId", "dbo.PlatformTypeEntities");
            DropForeignKey("dbo.GameEntities", "Publisher_EntityId", "dbo.PublisherEntities");
            DropForeignKey("dbo.OrderDetailsEntities", "Order_EntityId", "dbo.OrderEntities");
            DropIndex("dbo.CommentEntities", new[] { "Game_EntityId" });
            DropIndex("dbo.OrderDetailsEntities", new[] { "Game_EntityId" });
            DropIndex("dbo.OrderDetailsEntities", new[] { "Order_EntityId" });
            DropColumn("dbo.CommentEntities", "GameId");
            DropColumn("dbo.OrderDetailsEntities", "GameId");
            DropColumn("dbo.OrderDetailsEntities", "OrderId");
            RenameColumn(table: "dbo.CommentEntities", name: "Game_EntityId", newName: "GameId");
            RenameColumn(table: "dbo.GameInfoEntities", name: "EntityId", newName: "Id");
            RenameColumn(table: "dbo.GenreEntityGameEntities", name: "GenreEntity_EntityId", newName: "GenreEntity_Id");
            RenameColumn(table: "dbo.GenreEntityGameEntities", name: "GameEntity_EntityId", newName: "GameEntity_Id");
            RenameColumn(table: "dbo.PlatformTypeEntityGameEntities", name: "PlatformTypeEntity_EntityId", newName: "PlatformTypeEntity_Id");
            RenameColumn(table: "dbo.PlatformTypeEntityGameEntities", name: "GameEntity_EntityId", newName: "GameEntity_Id");
            RenameColumn(table: "dbo.GameEntities", name: "Publisher_EntityId", newName: "Publisher_Id");
            RenameColumn(table: "dbo.GenreEntities", name: "GenreEntity_EntityId", newName: "GenreEntity_Id");
            RenameColumn(table: "dbo.OrderDetailsEntities", name: "Game_EntityId", newName: "GameId");
            RenameColumn(table: "dbo.OrderDetailsEntities", name: "Order_EntityId", newName: "OrderId");
            RenameIndex(table: "dbo.GameEntities", name: "IX_Publisher_EntityId", newName: "IX_Publisher_Id");
            RenameIndex(table: "dbo.GameInfoEntities", name: "IX_EntityId", newName: "IX_Id");
            RenameIndex(table: "dbo.GenreEntities", name: "IX_GenreEntity_EntityId", newName: "IX_GenreEntity_Id");
            RenameIndex(table: "dbo.GenreEntityGameEntities", name: "IX_GenreEntity_EntityId", newName: "IX_GenreEntity_Id");
            RenameIndex(table: "dbo.GenreEntityGameEntities", name: "IX_GameEntity_EntityId", newName: "IX_GameEntity_Id");
            RenameIndex(table: "dbo.PlatformTypeEntityGameEntities", name: "IX_PlatformTypeEntity_EntityId", newName: "IX_PlatformTypeEntity_Id");
            RenameIndex(table: "dbo.PlatformTypeEntityGameEntities", name: "IX_GameEntity_EntityId", newName: "IX_GameEntity_Id");
            DropPrimaryKey("dbo.CommentEntities");
            DropPrimaryKey("dbo.GameEntities");
            DropPrimaryKey("dbo.GenreEntities");
            DropPrimaryKey("dbo.PlatformTypeEntities");
            DropPrimaryKey("dbo.PublisherEntities");
            DropPrimaryKey("dbo.OrderDetailsEntities");
            DropPrimaryKey("dbo.OrderEntities");
            AddColumn("dbo.CommentEntities", "Id", c => c.String(nullable: false, maxLength: 128));
            AddColumn("dbo.GameEntities", "Id", c => c.String(nullable: false, maxLength: 128));
            AddColumn("dbo.GenreEntities", "Id", c => c.String(nullable: false, maxLength: 128));
            AddColumn("dbo.PlatformTypeEntities", "Id", c => c.String(nullable: false, maxLength: 128));
            AddColumn("dbo.PublisherEntities", "Id", c => c.String(nullable: false, maxLength: 128));
            AddColumn("dbo.OrderDetailsEntities", "Id", c => c.String(nullable: false, maxLength: 128));
            AddColumn("dbo.OrderEntities", "Id", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.CommentEntities", "GameId", c => c.String(maxLength: 128));
            AlterColumn("dbo.OrderDetailsEntities", "GameId", c => c.String(maxLength: 128));
            AlterColumn("dbo.OrderDetailsEntities", "OrderId", c => c.String(maxLength: 128));
            AddPrimaryKey("dbo.CommentEntities", "Id");
            AddPrimaryKey("dbo.GameEntities", "Id");
            AddPrimaryKey("dbo.GenreEntities", "Id");
            AddPrimaryKey("dbo.PlatformTypeEntities", "Id");
            AddPrimaryKey("dbo.PublisherEntities", "Id");
            AddPrimaryKey("dbo.OrderDetailsEntities", "Id");
            AddPrimaryKey("dbo.OrderEntities", "Id");
            CreateIndex("dbo.CommentEntities", "GameId");
            CreateIndex("dbo.OrderDetailsEntities", "GameId");
            CreateIndex("dbo.OrderDetailsEntities", "OrderId");
            AddForeignKey("dbo.CommentEntities", "GameId", "dbo.GameEntities", "Id");
            AddForeignKey("dbo.GameInfoEntities", "Id", "dbo.GameEntities", "Id");
            AddForeignKey("dbo.GenreEntityGameEntities", "GameEntity_Id", "dbo.GameEntities", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PlatformTypeEntityGameEntities", "GameEntity_Id", "dbo.GameEntities", "Id", cascadeDelete: true);
            AddForeignKey("dbo.OrderDetailsEntities", "GameId", "dbo.GameEntities", "Id");
            AddForeignKey("dbo.GenreEntityGameEntities", "GenreEntity_Id", "dbo.GenreEntities", "Id", cascadeDelete: true);
            AddForeignKey("dbo.GenreEntities", "GenreEntity_Id", "dbo.GenreEntities", "Id");
            AddForeignKey("dbo.PlatformTypeEntityGameEntities", "PlatformTypeEntity_Id", "dbo.PlatformTypeEntities", "Id", cascadeDelete: true);
            AddForeignKey("dbo.GameEntities", "Publisher_Id", "dbo.PublisherEntities", "Id");
            AddForeignKey("dbo.OrderDetailsEntities", "OrderId", "dbo.OrderEntities", "Id");
            DropColumn("dbo.CommentEntities", "EntityId");
            DropColumn("dbo.GameEntities", "EntityId");
            DropColumn("dbo.GenreEntities", "EntityId");
            DropColumn("dbo.PlatformTypeEntities", "EntityId");
            DropColumn("dbo.PublisherEntities", "EntityId");
            DropColumn("dbo.OrderDetailsEntities", "EntityId");
            DropColumn("dbo.OrderEntities", "EntityId");
        }
        
        public override void Down()
        {
            AddColumn("dbo.OrderEntities", "EntityId", c => c.String(nullable: false, maxLength: 128));
            AddColumn("dbo.OrderDetailsEntities", "EntityId", c => c.String(nullable: false, maxLength: 128));
            AddColumn("dbo.PublisherEntities", "EntityId", c => c.String(nullable: false, maxLength: 128));
            AddColumn("dbo.PlatformTypeEntities", "EntityId", c => c.String(nullable: false, maxLength: 128));
            AddColumn("dbo.GenreEntities", "EntityId", c => c.String(nullable: false, maxLength: 128));
            AddColumn("dbo.GameEntities", "EntityId", c => c.String(nullable: false, maxLength: 128));
            AddColumn("dbo.CommentEntities", "EntityId", c => c.String(nullable: false, maxLength: 128));
            DropForeignKey("dbo.OrderDetailsEntities", "OrderId", "dbo.OrderEntities");
            DropForeignKey("dbo.GameEntities", "Publisher_Id", "dbo.PublisherEntities");
            DropForeignKey("dbo.PlatformTypeEntityGameEntities", "PlatformTypeEntity_Id", "dbo.PlatformTypeEntities");
            DropForeignKey("dbo.GenreEntities", "GenreEntity_Id", "dbo.GenreEntities");
            DropForeignKey("dbo.GenreEntityGameEntities", "GenreEntity_Id", "dbo.GenreEntities");
            DropForeignKey("dbo.OrderDetailsEntities", "GameId", "dbo.GameEntities");
            DropForeignKey("dbo.PlatformTypeEntityGameEntities", "GameEntity_Id", "dbo.GameEntities");
            DropForeignKey("dbo.GenreEntityGameEntities", "GameEntity_Id", "dbo.GameEntities");
            DropForeignKey("dbo.GameInfoEntities", "Id", "dbo.GameEntities");
            DropForeignKey("dbo.CommentEntities", "GameId", "dbo.GameEntities");
            DropIndex("dbo.OrderDetailsEntities", new[] { "OrderId" });
            DropIndex("dbo.OrderDetailsEntities", new[] { "GameId" });
            DropIndex("dbo.CommentEntities", new[] { "GameId" });
            DropPrimaryKey("dbo.OrderEntities");
            DropPrimaryKey("dbo.OrderDetailsEntities");
            DropPrimaryKey("dbo.PublisherEntities");
            DropPrimaryKey("dbo.PlatformTypeEntities");
            DropPrimaryKey("dbo.GenreEntities");
            DropPrimaryKey("dbo.GameEntities");
            DropPrimaryKey("dbo.CommentEntities");
            AlterColumn("dbo.OrderDetailsEntities", "OrderId", c => c.String());
            AlterColumn("dbo.OrderDetailsEntities", "GameId", c => c.String());
            AlterColumn("dbo.CommentEntities", "GameId", c => c.String());
            DropColumn("dbo.OrderEntities", "Id");
            DropColumn("dbo.OrderDetailsEntities", "Id");
            DropColumn("dbo.PublisherEntities", "Id");
            DropColumn("dbo.PlatformTypeEntities", "Id");
            DropColumn("dbo.GenreEntities", "Id");
            DropColumn("dbo.GameEntities", "Id");
            DropColumn("dbo.CommentEntities", "Id");
            AddPrimaryKey("dbo.OrderEntities", "EntityId");
            AddPrimaryKey("dbo.OrderDetailsEntities", "EntityId");
            AddPrimaryKey("dbo.PublisherEntities", "EntityId");
            AddPrimaryKey("dbo.PlatformTypeEntities", "EntityId");
            AddPrimaryKey("dbo.GenreEntities", "EntityId");
            AddPrimaryKey("dbo.GameEntities", "EntityId");
            AddPrimaryKey("dbo.CommentEntities", "EntityId");
            RenameIndex(table: "dbo.PlatformTypeEntityGameEntities", name: "IX_GameEntity_Id", newName: "IX_GameEntity_EntityId");
            RenameIndex(table: "dbo.PlatformTypeEntityGameEntities", name: "IX_PlatformTypeEntity_Id", newName: "IX_PlatformTypeEntity_EntityId");
            RenameIndex(table: "dbo.GenreEntityGameEntities", name: "IX_GameEntity_Id", newName: "IX_GameEntity_EntityId");
            RenameIndex(table: "dbo.GenreEntityGameEntities", name: "IX_GenreEntity_Id", newName: "IX_GenreEntity_EntityId");
            RenameIndex(table: "dbo.GenreEntities", name: "IX_GenreEntity_Id", newName: "IX_GenreEntity_EntityId");
            RenameIndex(table: "dbo.GameInfoEntities", name: "IX_Id", newName: "IX_EntityId");
            RenameIndex(table: "dbo.GameEntities", name: "IX_Publisher_Id", newName: "IX_Publisher_EntityId");
            RenameColumn(table: "dbo.OrderDetailsEntities", name: "OrderId", newName: "Order_EntityId");
            RenameColumn(table: "dbo.OrderDetailsEntities", name: "GameId", newName: "Game_EntityId");
            RenameColumn(table: "dbo.GenreEntities", name: "GenreEntity_Id", newName: "GenreEntity_EntityId");
            RenameColumn(table: "dbo.GameEntities", name: "Publisher_Id", newName: "Publisher_EntityId");
            RenameColumn(table: "dbo.PlatformTypeEntityGameEntities", name: "GameEntity_Id", newName: "GameEntity_EntityId");
            RenameColumn(table: "dbo.PlatformTypeEntityGameEntities", name: "PlatformTypeEntity_Id", newName: "PlatformTypeEntity_EntityId");
            RenameColumn(table: "dbo.GenreEntityGameEntities", name: "GameEntity_Id", newName: "GameEntity_EntityId");
            RenameColumn(table: "dbo.GenreEntityGameEntities", name: "GenreEntity_Id", newName: "GenreEntity_EntityId");
            RenameColumn(table: "dbo.GameInfoEntities", name: "Id", newName: "EntityId");
            RenameColumn(table: "dbo.CommentEntities", name: "GameId", newName: "Game_EntityId");
            AddColumn("dbo.OrderDetailsEntities", "OrderId", c => c.String());
            AddColumn("dbo.OrderDetailsEntities", "GameId", c => c.String());
            AddColumn("dbo.CommentEntities", "GameId", c => c.String());
            CreateIndex("dbo.OrderDetailsEntities", "Order_EntityId");
            CreateIndex("dbo.OrderDetailsEntities", "Game_EntityId");
            CreateIndex("dbo.CommentEntities", "Game_EntityId");
            AddForeignKey("dbo.OrderDetailsEntities", "Order_EntityId", "dbo.OrderEntities", "EntityId");
            AddForeignKey("dbo.GameEntities", "Publisher_EntityId", "dbo.PublisherEntities", "EntityId");
            AddForeignKey("dbo.PlatformTypeEntityGameEntities", "PlatformTypeEntity_EntityId", "dbo.PlatformTypeEntities", "EntityId", cascadeDelete: true);
            AddForeignKey("dbo.GenreEntities", "GenreEntity_EntityId", "dbo.GenreEntities", "EntityId");
            AddForeignKey("dbo.GenreEntityGameEntities", "GenreEntity_EntityId", "dbo.GenreEntities", "EntityId", cascadeDelete: true);
            AddForeignKey("dbo.OrderDetailsEntities", "Game_EntityId", "dbo.GameEntities", "EntityId");
            AddForeignKey("dbo.PlatformTypeEntityGameEntities", "GameEntity_EntityId", "dbo.GameEntities", "EntityId", cascadeDelete: true);
            AddForeignKey("dbo.GenreEntityGameEntities", "GameEntity_EntityId", "dbo.GameEntities", "EntityId", cascadeDelete: true);
            AddForeignKey("dbo.GameInfoEntities", "EntityId", "dbo.GameEntities", "EntityId");
            AddForeignKey("dbo.CommentEntities", "Game_EntityId", "dbo.GameEntities", "EntityId");
        }
    }
}
