// <auto-generated />
namespace GameStore.DataAccess.MSSQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class delete_GameId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(delete_GameId));
        
        string IMigrationMetadata.Id
        {
            get { return "201707230716479_delete_GameId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
